@startuml

entity "User" as User {
  *user_id : int <<PK>>
  --
  username: str
  password_hash: str
  email: str
  date_of_birth: date
  created_at: datetime
}

entity "HealthIndex" as HealthIndex {
  *health_index_id : int <<PK>>
  --
  user_id: int <<FK>>
  recorded_at: datetime
  highBp: int
  highChol: int
  cholCheck: int 
  weight: int 
  height: int 
  Smoker: int
  stroke: int 
  heartDiseaseOrAttack: int 
  physActivity: int 
  HvyAlcoholConsump: int 
  AnyHealthcare: int 
  NoDocbcCost: int
  GenHlth: int	
  MentHlth: int	
  PhysHlth: int
  DiffWalkL: int 	
  Sex: int
  Age: int
  Education: int	
  Income: int
}

entity "ChatHistory" as History {
  *history_id : int <<PK>>
  --
  user_id: int <<FK>>
  started_at: datetime
  ended_at: datetime
  prediction_result : str
}

entity "Message" as Message {
  *message_id: int <<PK>>
  --
  history_id: int <<FK>>
  sender_type: str' "user" hoặc "bot"
  content: str
  sent_at: datetime
}

' Quan hệ:
User ||--o{ HealthIndex: "1:N"
User ||--o{ History: "1:N"
History ||--o{ Message: "1:N"

@enduml
